-- Ver a representatividade dentro dos partidos, tentando verificar aqueles mais progressitas.
WITH tb_candidates as (
	SELECT SQ_CANDIDATO,
		SG_UF,
		DS_CARGO,
		SG_PARTIDO,
		NM_PARTIDO,
		DT_NASCIMENTO,
		DS_GENERO,
		DS_GRAU_INSTRUCAO,
		DS_COR_RACA,
		DS_OCUPACAO,
		NM_UE,
		NM_CANDIDATO
	FROM tb_candidaturas
),
tb_total_bens as (
	SELECT SQ_CANDIDATO,
		SUM(cast(replace(VR_BEM_CANDIDATO,',', '.') as DECIMAL(15,2))) as total_bens
	from tb_bens
	group by 1
),
tb_info_completa_cand as (
	SELECT t1.*,
		COALESCE(t2.total_bens, 0) as total_bens

	FROM tb_candidates as t1
	LEFT JOIN tb_total_bens as t2
	ON t1.SQ_CANDIDATO = t2.SQ_CANDIDATO
),
tb_group_uf as (
	SELECT
		SG_PARTIDO,
		NM_PARTIDO,
		SG_UF,
		AVG(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS tx_gen_feminino,
		SUM(CASE WHEN DS_GENERO = 'FEMININO' THEN 1 ELSE 0 END) AS total_gen_feminino,
		AVG(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS tx_cor_raca_preta,
		SUM(CASE WHEN DS_COR_RACA = 'PRETA' THEN 1 ELSE 0 END) AS total_cor_raca_preta,
        AVG(CASE WHEN DS_COR_RACA IN ('PRETA', 'PARDA') THEN 1 ELSE 0 END) AS tx_cor_raca_preta_parda,
        SUM(CASE WHEN DS_COR_RACA IN ('PRETA', 'PARDA') THEN 1 ELSE 0 END) AS total_cor_raca_preta_parda,
		AVG(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS tx_cor_raca_nao_branca,
		SUM(CASE WHEN DS_COR_RACA <> 'BRANCA' THEN 1 ELSE 0 END) AS total_cor_raca_nao_branca,
		count(*) AS total_candidaturas
	FROM tb_info_completa_cand as t1
	GROUP BY 1,2,3
),
tb_all AS (

	SELECT
		SG_PARTIDO,
		NM_PARTIDO,
		SUM(CASE WHEN SG_UF = 'AC' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_AC,
		SUM(CASE WHEN SG_UF = 'AL' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_AL,
		SUM(CASE WHEN SG_UF = 'AM' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_AM,
		SUM(CASE WHEN SG_UF = 'AP' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_AP,
		SUM(CASE WHEN SG_UF = 'BA' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_BA,
		SUM(CASE WHEN SG_UF = 'CE' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_CE,
		SUM(CASE WHEN SG_UF = 'ES' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_ES,
		SUM(CASE WHEN SG_UF = 'GO' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_GO,
		SUM(CASE WHEN SG_UF = 'MA' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_MA,
		SUM(CASE WHEN SG_UF = 'MG' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_MG,
		SUM(CASE WHEN SG_UF = 'MS' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_MS,
		SUM(CASE WHEN SG_UF = 'MT' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_MT,
		SUM(CASE WHEN SG_UF = 'PA' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_PA,
		SUM(CASE WHEN SG_UF = 'PB' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_PB,
		SUM(CASE WHEN SG_UF = 'PE' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_PE,
		SUM(CASE WHEN SG_UF = 'PI' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_PI,
		SUM(CASE WHEN SG_UF = 'PR' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_PR,
		SUM(CASE WHEN SG_UF = 'RJ' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_RJ,
		SUM(CASE WHEN SG_UF = 'RO' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_RO,
		SUM(CASE WHEN SG_UF = 'RS' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_RS,
		SUM(CASE WHEN SG_UF = 'SC' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_SC,
		SUM(CASE WHEN SG_UF = 'SE' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_SE,
		SUM(CASE WHEN SG_UF = 'SP' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_SP,
		SUM(CASE WHEN SG_UF = 'TO' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_TO,
		SUM(CASE WHEN SG_UF = 'RN' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_RN,
		SUM(CASE WHEN SG_UF = 'RR' THEN tx_gen_feminino ELSE 0 END) AS tx_gen_feminino_RR,
		1.0 * SUM(total_gen_feminino) / SUM(total_candidaturas) AS tx_gen_feminino_BR,

		SUM(CASE WHEN SG_UF = 'AC' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_AC,
		SUM(CASE WHEN SG_UF = 'AL' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_AL,
		SUM(CASE WHEN SG_UF = 'AM' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_AM,
		SUM(CASE WHEN SG_UF = 'AP' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_AP,
		SUM(CASE WHEN SG_UF = 'BA' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_BA,
		SUM(CASE WHEN SG_UF = 'CE' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_CE,
		SUM(CASE WHEN SG_UF = 'ES' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_ES,
		SUM(CASE WHEN SG_UF = 'GO' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_GO,
		SUM(CASE WHEN SG_UF = 'MA' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_MA,
		SUM(CASE WHEN SG_UF = 'MG' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_MG,
		SUM(CASE WHEN SG_UF = 'MS' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_MS,
		SUM(CASE WHEN SG_UF = 'MT' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_MT,
		SUM(CASE WHEN SG_UF = 'PA' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_PA,
		SUM(CASE WHEN SG_UF = 'PB' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_PB,
		SUM(CASE WHEN SG_UF = 'PE' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_PE,
		SUM(CASE WHEN SG_UF = 'PI' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_PI,
		SUM(CASE WHEN SG_UF = 'PR' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_PR,
		SUM(CASE WHEN SG_UF = 'RJ' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_RJ,
		SUM(CASE WHEN SG_UF = 'RO' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_RO,
		SUM(CASE WHEN SG_UF = 'RS' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_RS,
		SUM(CASE WHEN SG_UF = 'SC' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_SC,
		SUM(CASE WHEN SG_UF = 'SE' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_SE,
		SUM(CASE WHEN SG_UF = 'SP' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_SP,
		SUM(CASE WHEN SG_UF = 'TO' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_TO,
		SUM(CASE WHEN SG_UF = 'RN' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_RN,
		SUM(CASE WHEN SG_UF = 'RR' THEN tx_cor_raca_preta ELSE 0 END) AS tx_cor_raca_preta_RR,
		1.0 * SUM(total_cor_raca_preta) / SUM(total_candidaturas) AS tx_cor_raca_preta_BR,

		SUM(CASE WHEN SG_UF = 'AC' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_AC,
		SUM(CASE WHEN SG_UF = 'AL' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_AL,
		SUM(CASE WHEN SG_UF = 'AM' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_AM,
		SUM(CASE WHEN SG_UF = 'AP' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_AP,
		SUM(CASE WHEN SG_UF = 'BA' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_BA,
		SUM(CASE WHEN SG_UF = 'CE' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_CE,
		SUM(CASE WHEN SG_UF = 'ES' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_ES,
		SUM(CASE WHEN SG_UF = 'GO' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_GO,
		SUM(CASE WHEN SG_UF = 'MA' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_MA,
		SUM(CASE WHEN SG_UF = 'MG' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_MG,
		SUM(CASE WHEN SG_UF = 'MS' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_MS,
		SUM(CASE WHEN SG_UF = 'MT' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_MT,
		SUM(CASE WHEN SG_UF = 'PA' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_PA,
		SUM(CASE WHEN SG_UF = 'PB' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_PB,
		SUM(CASE WHEN SG_UF = 'PE' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_PE,
		SUM(CASE WHEN SG_UF = 'PI' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_PI,
		SUM(CASE WHEN SG_UF = 'PR' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_PR,
		SUM(CASE WHEN SG_UF = 'RJ' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_RJ,
		SUM(CASE WHEN SG_UF = 'RO' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_RO,
		SUM(CASE WHEN SG_UF = 'RS' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_RS,
		SUM(CASE WHEN SG_UF = 'SC' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_SC,
		SUM(CASE WHEN SG_UF = 'SE' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_SE,
		SUM(CASE WHEN SG_UF = 'SP' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_SP,
		SUM(CASE WHEN SG_UF = 'TO' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_TO,
		SUM(CASE WHEN SG_UF = 'RN' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_RN,
		SUM(CASE WHEN SG_UF = 'RR' THEN tx_cor_raca_nao_branca ELSE 0 END) AS tx_cor_raca_nao_branca_RR,
		1.0 * SUM(total_cor_raca_nao_branca) / SUM(total_candidaturas) AS tx_cor_raca_nao_branca_BR,

		SUM(CASE WHEN SG_UF = 'AC' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_AC,
		SUM(CASE WHEN SG_UF = 'AL' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_AL,
		SUM(CASE WHEN SG_UF = 'AM' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_AM,
		SUM(CASE WHEN SG_UF = 'AP' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_AP,
		SUM(CASE WHEN SG_UF = 'BA' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_BA,
		SUM(CASE WHEN SG_UF = 'CE' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_CE,
		SUM(CASE WHEN SG_UF = 'ES' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_ES,
		SUM(CASE WHEN SG_UF = 'GO' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_GO,
		SUM(CASE WHEN SG_UF = 'MA' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_MA,
		SUM(CASE WHEN SG_UF = 'MG' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_MG,
		SUM(CASE WHEN SG_UF = 'MS' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_MS,
		SUM(CASE WHEN SG_UF = 'MT' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_MT,
		SUM(CASE WHEN SG_UF = 'PA' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_PA,
		SUM(CASE WHEN SG_UF = 'PB' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_PB,
		SUM(CASE WHEN SG_UF = 'PE' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_PE,
		SUM(CASE WHEN SG_UF = 'PI' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_PI,
		SUM(CASE WHEN SG_UF = 'PR' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_PR,
		SUM(CASE WHEN SG_UF = 'RJ' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_RJ,
		SUM(CASE WHEN SG_UF = 'RO' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_RO,
		SUM(CASE WHEN SG_UF = 'RS' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_RS,
		SUM(CASE WHEN SG_UF = 'SC' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_SC,
		SUM(CASE WHEN SG_UF = 'SE' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_SE,
		SUM(CASE WHEN SG_UF = 'SP' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_SP,
		SUM(CASE WHEN SG_UF = 'TO' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_TO,
		SUM(CASE WHEN SG_UF = 'RN' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_RN,
		SUM(CASE WHEN SG_UF = 'RR' THEN tx_cor_raca_preta_parda ELSE 0 END) AS tx_cor_raca_preta_parda_RR,
		1.0 * SUM(total_cor_raca_preta_parda) / SUM(total_candidaturas) AS tx_cor_raca_preta_parda_BR,

		SUM(total_gen_feminino) AS total_gen_feminino,
		SUM(total_cor_raca_preta) AS total_cor_raca_preta,
		SUM(total_cor_raca_nao_branca) AS total_cor_raca_nao_branca,
		SUM(total_cor_raca_preta_parda) AS total_cor_raca_preta_parda,
		SUM(total_candidaturas) AS total_candidaturas

	FROM tb_group_uf GROUP BY 1,2
)

SELECT * FROM tb_all;
